### ISSUE TITLE
[dev branch] Is It working actually for you ?

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#11]
(Sinusbot 0.10.6-ea49bdc) Because for me not, got this error on console log via chrome : 

`GET http://ipofmyvps:8101/api/v1/bot/i/20372271-2d4d-4fb2-8e88-a680c0cea32e/stream/uQHwWHsiaSI6ImFjZjVjZWM3LWFmMjAtNDJkNi04OTMyLTA3ZWZhNDliNDdmMSIsImIiOiJkNGY1ZmExNS05MTk4LTRkNjctYTZmOC1lYzhmMDA1OTA0MTMiLCJ1AVbwW2RtaW4iLCJ0IjoxNTEwMTk2NjcyLCJzIjoiYjA5OTg2NWFlN2Q3ZjY0ZjU1ZTM1MmNjMDM5MDgyZDllZTkyNzgzNTYyMTU2OGUzYTU0NDQ5Yjc5YWMzMmVkYSJ9 401 (Unauthorized)`

**Comment by Zahzi** [comment]
Nope. Still having the same issues as in #8.

The dev branch just includes an API class update, bootstrap URL update, and a readme update IIRC.
