### ISSUE TITLE
Any Help please ? 

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#3]
When I put all of your folder and when it's configure I got this : http://sinusbot.zalati.fr/

**Comment by Zahzi** [comment]
@Zalatis Your PHP appears to be configured incorrectly. Make sure to install PHP and the PHP mod for apache. After doing that, make sure to restart apache.

**Comment by ihateniggers123** [comment]
Yes, it seems to me that you sir need to download the latest version of PHP from pornhub.com/gay, after doing so make sure to configure your penis correctly and be ready to ejaculate all over your config files!

**Comment by Zalatis** [comment]
Ok, now I just have a problem with the player and the song name

**Comment by Zahzi** [comment]
@Zalatis Double check your config.php file. It appears that the UUID of the bot isn't set. Obtain the UUID from your instance settings. ![alt text](https://www.zahzi.us/screenshots/1485655995.png "Logo Title Text 1")
If this doesn't work, please paste your config.php. Make sure to remove any personal information/passwords.

**Comment by Zalatis** [comment]
Done, got sound now but no image & also a problem under the player 
Really thanks for your support ! :D

**Comment by Zahzi** [comment]
@Zalatis I think I see what you mean under the player. I cleared my cache/cookies and it went away.

**Comment by Zalatis** [comment]
Can we also put an other default image for the player when it's not a youtube link ?

**Comment by Zahzi** [comment]
@Zalatis The default file is located at resources/unknownimg.png in your SinusBot directory. You should be able to upload your own file there if you want.

I might add a config option in the future.

**Comment by Zalatis** [comment]
It's ok it works, I go found an other image and that's all :)
Thanks for your support once again and have a good day/night :)

**Comment by Zahzi** [comment]
No problem.

**Comment by Zalatis** [comment]
Can we also use the link look like : http://sinusbot.zalati.fr:8101/api/v1/bot/i/20372271-2d4d-4fb2-8e88-a680c0cea32e/stream/uQHwWHsiaSI6ImFjZjVjZWM3LWFmMjAtNDJkNi04OTMyLTA3ZWZhNDliNDdmMSIsImIiOiJkNGY1ZmExNS05MTk4LTRkNjctYTZmOC1lYzhmMDA1OTA0MTMiLCJ1AVbwW2RtaW4iLCJ0IjoxNDg1Njk5MTI5LCJzIjoiZWQ4ZGNmY2E0MmFmNmRlMDQxMDFlYjg0ZjZkZDUwZDY5NDYzNWZjMTBlYThjYmM2MDc4YmRlOTgxNDc2ZGNiNCJ9 ?
Because sometimes it says "Forbidden"

**Comment by Zahzi** [comment]
@Zalatis That's the source of the stream that this player uses from SinusBot's API (```/api/v1/bot/i/:instanceId/stream/:token```). Unfortunately, the token expires after it's used/after some time has passed. If you reload the player it will get a new token and stream url. Currently, you'll have to do this whenever the player freezes. I plan to improve this in the future.

**Comment by Zahzi** [comment]
@Zalatis This problem should be resolved in v1.1 as of commit 6dab664. There's also a reload button if it doesn't trigger automatically. It's currently on the dev branch. 

Also, related to this issue, v1.1 has a config option to change the default image.
