### ISSUE TITLE
Feature : Add feature for support Temp artist and title

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#4]
Like the title said, it is possible to add a feature for support temp artist and temp title for the SinusBot-Stream (Google research) Like music streaming directly by Youtube Interface : http://radio.zalati.fr/

**Comment by Zahzi** [comment]
I'm not sure I understand what you mean. When I install the YT interface and play something from it, the song name updates correctly. Can you provide more detail?

**Comment by Zalatis** [comment]
Hum, The title update correctly but when you click on the title normally you are redirected to google research no ?

**Comment by Zalatis** [comment]
And if we put the link of a radio, the title of music stream by the radio don't shows

**Comment by Zahzi** [comment]
For the youtube interface, getStatus() from the API produced the following:
```Array ( [v] => 0.9.16-10f0fad [currentTrack] => Array ( [v] => 0 [uuid] => [parent] => [type] => temp [duration] => 533000 [title] => Sax Roll'd [artist] => ProteloZonic1 ) [position] => 288605 [running] => 1 [playing] => 1 [playlist] => e4b99c2a-a9b5-4ff9-b7e9-bda99f685e3d [playlistTrack] => 3 [shuffle] => 1 [repeat] => 1 [volume] => 50 [needsRestart] => [queueLen] => 0 [queueVersion] => 0 [modes] => 0 [downloaded] => 0 [serverUID] => NrsGtdP1nDn3l5yCynx2xRu3sLc= [flags] => 0 [muted] => 0 [connStatus] => Array ( [status] => 4 [connectedTime] => 21014703 [latency] => 0 [packetLoss] => 0 [packetLossS2C] => 0 [packetLossC2S] => 0 [bytesSent] => 256036392 [bytesRecv] => 2082662 [bandwidthSent] => 11735 [bandwidthRecv] => 81 [channelId] => 24 ) [streamListeners] => 1 )```

There isn't a link to the video or a thumbnail embedded. This is how SinusBot-Stream is getting all of its data, and I can't think of another way to do it without using the API at the moment (except for searching the name, and taking the first youtube result, but this could be pretty inaccurate).

For the URL on the title, it still seems to work. It doesn't provide a direct youtube link, because there isn't one in the metadata, but it provides a link to a google search. ![](http://zahzi.us/screenshots/1486330644.png)

If I download the song normally with youtube-dl without the interface, or use the "download" function in the youtube interface instead of play I get the following:
```Array ( [v] => 0.9.16-10f0fad [currentTrack] => Array ( [v] => 1 [uuid] => 9481454f-fc7e-4191-a33b-8e9177734442 [parent] => [type] => [codec] => - [duration] => 532632 [bitrate] => 2377566 [samplerate] => 1 [filesize] => 9335031 [filename] => https://www.youtube.com/watch?v=Tg4u7ko333U [title] => Sax Roll'd [artist] => ProteloZonic1 [thumbnail] => a85bb6071c2a172351eec3da1efabf6fdb830e50648087e390ba8d384d3482de.jpg ) [position] => 12061 [running] => 1 [playing] => 1 [playlist] => [playlistTrack] => -1 [shuffle] => 1 [repeat] => 1 [volume] => 50 [needsRestart] => [queueLen] => 0 [queueVersion] => 0 [modes] => 0 [downloaded] => 0 [serverUID] => NrsGtdP1nDn3l5yCynx2xRu3sLc= [flags] => 0 [muted] => 0 [connStatus] => Array ( [status] => 4 [connectedTime] => 21475912 [latency] => 0 [packetLoss] => 0 [packetLossS2C] => 0 [packetLossC2S] => 0 [bytesSent] => 261683390 [bytesRecv] => 2128307 [bandwidthSent] => 12389 [bandwidthRecv] => 81 [channelId] => 24 ) [streamListeners] => 1 )```

Note that these contain the youtube link and a thumbnail, and therefore SinusBot-Stream can use it.


As far as the radio stations go, I can see that it doesn't work correctly: ![](http://zahzi.us/screenshots/1486330862.png), but the metadata seems to be there:
``` Array ( [v] => 0.9.16-10f0fad [currentTrack] => Array ( [v] => 0 [uuid] => [parent] => [type] => url [filename] => http://streaming208.radionomy.com:80/180 [title] => 180 [tempArtist] => Queen [tempTitle] => Another one bites the dust ) [position] => 34194 [running] => 1 [playing] => 1 [playlist] => [playlistTrack] => -1 [shuffle] => 1 [repeat] => 1 [volume] => 50 [needsRestart] => [queueLen] => 0 [queueVersion] => 0 [modes] => 0 [downloaded] => 579213 [serverUID] => NrsGtdP1nDn3l5yCynx2xRu3sLc= [flags] => 0 [muted] => 0 [connStatus] => Array ( [status] => 4 [connectedTime] => 21706546 [latency] => 0 [packetLoss] => 0 [packetLossS2C] => 0 [packetLossC2S] => 0 [bytesSent] => 264506548 [bytesRecv] => 2151570 [bandwidthSent] => 11982 [bandwidthRecv] => 121 [channelId] => 24 ) [streamListeners] => 1 )```

I'll look into fixing this. It *shouldn't* be too hard.

**Comment by Zalatis** [comment]
Small bug in the util.php Line 19 :       $link = 'https://www.google.com/search?q=' . getTrack();

I just replace by    :   $link = 'https://www.google.com/search?q='.getTrack();

And the research work for the youtube video that is not downloaded

**Comment by ihateniggers123** [comment]
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.

**Comment by Zahzi** [comment]
@Zalatis That shouldn't make a difference. The space is outside of the quote. 
"a" . "b" is the same as "a"."b"
Both output "ab"

I found out how to make the radio work. It just uses "tempArtist" and "tempTitle" when type="url". I'll let you know when it's implemented.

Not sure what you mean in your last sentence.

**Comment by ihateniggers123** [comment]
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.

**Comment by ihateniggers123** [comment]
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.

**Comment by ihateniggers123** [comment]
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.
J'aime des baguttes, aimez-vous une baguette? Im sûr que si vous pousser une baguette dans votre cul, tous les bugs seront corrigés.

**Comment by Zalatis** [comment]
I don't know sometimes the google result result to the titlte of the music sometime not

**Comment by Zahzi** [comment]
@Zalatis If the actual link to the source can't be found, it will default to a google link. If the link to the youtube video is in the metadata, it will link directly there.

**Comment by ihateniggers123** [comment]
@Zalatis yes retard learn to read code

**Comment by Zalatis** [comment]
Mmmmh Okay, I will try to find some feature that you can improve :3

**Comment by Zahzi** [comment]
Fixed in commit 51efa0f
