### ISSUE TITLE
Get artist - song with youtube-dl

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#6]
![sans titre](https://user-images.githubusercontent.com/16846453/28436900-f2899e64-6d98-11e7-8b9d-1bbb543970eb.png)

Because actually it just give Title not artist

**Comment by Zahzi** [comment]
Are you running v1.1.4?

It seems to be working fine for me. Please give me step by step instructions on how to replicate it. Here's what I did, where it seems to be functioning as intended.:
1. Download the song, for example from your screenshot: !ytdl https://www.youtube.com/watch?v=C6MOKXm8x50
2. Open up sinusbot-stream and few the artist: ![image](https://files.zahzi.us/screenshots/1500589344.png)

**Comment by Zalatis** [comment]
I'm using the feature that sinusbot enable that is make a playlist using youtube-dl
![sans titre](https://user-images.githubusercontent.com/16846453/28441523-83219dca-6dab-11e7-92b4-239db990ec85.png)

**Comment by Zahzi** [comment]
Hmm. I'm unable to play songs downloaded in this way for some reason. 

Can you give me a few pieces of information?
- A screenshot of your sinusbot webpanel showing the song/artist playing
- A screenshot of SinusBot-Stream while playing the song that is causing the issue
- The current status information. Get this by sending a POST request to your.url/SinusBot-Stream/util.php with the varible "status" set. For example with CURL: ```curl --data "status=status" https://sinusbot.zahzi.us/SinusBot-Stream-dev/util.php``` and paste me the full results.

**Comment by Zalatis** [comment]
`Array
(
    [v] => 0.9.20-a9b8dc6
    [currentTrack] => Array
        (
            [v] => 0
            [uuid] =>
            [parent] =>
            [type] => ytdl
            [title] => Linkin Park (Reanimation)
            [album] => P5hng Me A*wy
        )

    [position] => 107994
    [running] => 1
    [playing] => 1
    [playlist] => 8c756c20-fa27-4fd5-8a7e-d8b22c61eace
    [playlistTrack] => 82
    [shuffle] => 1
    [repeat] => 1
    [volume] => 50
    [needsRestart] =>
    [queueLen] => 0
    [queueVersion] => 0
    [modes] => 0
    [downloaded] => 1234550114
    [serverUID] => Y1JeK/W8Uk84nwYpn5fXBBoZFvo=
    [flags] => 0
    [muted] => 0
    [connStatus] => Array
        (
            [status] => 4
            [connectedTime] => 73313494
            [latency] => 1
            [packetLoss] => 0
            [packetLossS2C] => 0
            [packetLossC2S] => 0
            [bytesSent] => 887190995
            [bytesRecv] => 14794646
            [bandwidthSent] => 12159
            [bandwidthRecv] => 82
            [channelId] => 65
        )

    [streamListeners] => 0
)
`

but for all other informations you want this is the same because none music is stored on my bots all are stream from youtubedl
then the artist column is not show up

![](https://user-images.githubusercontent.com/16846453/28436900-f2899e64-6d98-11e7-8b9d-1bbb543970eb.png)

**Comment by Zahzi** [comment]
Hmm. Okay. As far as I can see there is no  artist specified for this song, and probably the others that are similar and not working. If you look at the status that the api output above, there is just title and album. 

I don't think that there is anything that I can do to get the artist if it's not in the status.

**Comment by Zalatis** [comment]
Okay, thanks for your answers :)
