### ISSUE TITLE
[Enhancement] Add youtube link redirect to the video directly

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#7]
Like in the YT-search 2.1 (by Patrick15a) from Sinusbot Forum

It gave the possibility to get the direct link to the youtube video streamed by youtube-dl

I don't know if you can make an adaptation of this script for the SinusBot-Stream :)

Take a Look to the code : 

-----------------------------------------------------------------------------------------------------------

registerPlugin({
    name: 'YT-Search',
    version: '2.1',
    description: 'Search the current track on YouTube!',
    author: 'Patrick15a <patrick15a@myfilehost.de>',
	vars: [
		{
			name: 'ytCommand',
			title: 'YouTube Search-Command',
			type: 'string',
			placeholder: 'Default: !ytsearch'
		},
		{
            name: 'scCommand',
            title: 'SoundCloud Search-Command',
            type: 'string',
            placeholder: 'Default: !scsearch'
		},
		{
			name: 'prefix',
			title: 'Prefix',
			type: 'string',
			placeholder: 'Default: [b][COLOR=#aa0000][[/COLOR][COLOR=#005500]YT-Search[/COLOR][COLOR=#aa0000]][/COLOR][/b]'
		}
	]
}, function(sinusbot, config) {
	
`	var backend = require('backend');
	var event = require('event');
	var audio = require('audio');
	var media = require('media');
	
	//Set Default's
	if (typeof config.prefix == 'undefined' || config.prefix === '') {
		var prefix = '[b][COLOR=#aa0000][[/COLOR][COLOR=#005500]YTsearch[/COLOR][COLOR=#aa0000]][/COLOR][/b]';
	}
	if (typeof config.ytCommand == 'undefined' || config.ytCommand === '') {
		var ytcmd = '!ytsearch';
	}
	if (typeof config.scCommand == 'undefined' || config.scCommand === '') {
        var sccmd = '!scsearch';
	}
	
	//Get current TrackInfos
	function getTrack() {
		var track = media.getCurrentTrack();
		
		if (typeof track.tempTitle() != 'undefined' && track.tempTitle() != '') {
			var title = track.tempTitle();
		} else if (track.title() != 'undefined' && track.title() != '') {
			var title = track.title();
		} else {
			var title = '';
		}
		if (typeof track.tempArtist() != 'undefined' && track.tempArtist() != '') {
			var artist = track.tempArtist();
        } else if (track.artist() != 'undefined' && track.artist() != '') {
			var artist = track.artist();
		} else if (typeof track.album() != 'undefined' && track.album() != ''){
			var artist = track.album();
		} else {
			var artist = '';
		}
		
		title = title.replace(/ /g, '+');
		title = title.replace(/&/g, '%26');
		title = title.replace(/'?'/g, '%3F');
		
		artist = artist.replace(/ /g, '+');
		artist = artist.replace(/&/g, '%26');
		artist = artist.replace(/'?'/g, '%3F');
		
		var search = artist + '+-+' + title;
		
		return search;
	}
	
	//Create Search-link
	function getSearchLink(provider) {
        
        var search = getTrack();
        
		if (provider == 'youtube') {
            var track = media.getCurrentTrack();
			if (track.type() == 'ytdl' && typeof track.url() != 'undefined') {
				var ytwatch = 'https://www.youtube.com/watch?v='
				var ytlink = ytwatch + track.url().split('url=')[1];
				var finishlink = '[URL=' + ytlink + ']Youtube[/URL]';
			} else {
				
				var ytsearchquery = 'https://www.youtube.com/results?search_query=';
				var ytlink = ytsearchquery + search;
				var finishlink = '[URL=' + ytlink + ']Youtube[/URL]';
			}
			
            
			
		} else if (provider == 'soundcloud') {
            
            var scsearchquery = 'https://soundcloud.com/search?q=';
            var sclink = scsearchquery + search;
            
            var finishlink = '[URL=' + sclink + ']SoundCloud[/URL]';
			
		}
		
		return finishlink;
	}
	
	//Send Message with Search-Link to User
	event.on('chat', function(ev) {
		
		if (audio.isPlaying()) {
			switch (ev.text) {
				case ytcmd:
					link = getSearchLink('youtube');
					ev.client.chat(prefix + ' Search the current track on ' + link + '.');
				break;
				
				case sccmd:
					link = getSearchLink('soundcloud');
					ev.client.chat(prefix + ' Search the current track on ' + link + '.');
				break;
			}
		} else {
			switch (ev.text) {
				case ytcmd:
					ev.client.chat(prefix + ' Sorry but the Bot is currently not playing music.');
				break;
				
				case sccmd:
					ev.client.chat(prefix + ' Sorry but the Bot is currently not playing music.');
				break;
			}
		}
		
	});
});`

**Comment by Zahzi** [comment]
It /should/ always be doing this when possible. It currently looks at the following values: 

 ```
$status['currentTrack']['filename']
$status['currentTrack']['album'],
$status['currentTrack']['artist']
```
If any of them is a valid URL, it links that. If none are, it links a google search. From looking at the status output when doing !yt <song>, I don't see any URL specified. I always installed the !ytsearch script that you referenced above, and its output was "Search the current track on youtube".

If you find an example where !ytsearch works and my method doesn't, let me know and I'll try to make it work. If you do find an example of this, send me the current status (eg ```curl --data "status=status" https://sinusbot.zahzi.us/SinusBot-Stream-dev/util.php```

I also could add an option to link a youtube search instead of a google search...
