### ISSUE TITLE
[Not Working] With Sinusbot

### ISSUE THREAD

**Issue by Zalatis** [Zahzi/SinusBot-Stream#8]
SinusBot (0.10.7-a91e4b6)

**Comment by Zahzi** [comment]
The problem seems to relate to logging into the API.

https://forum.sinusbot.com/threads/api-login.4262/#post-23181

Will look into fixing API class.

**Comment by Zahzi** [comment]
Flyth has confirmed that it's an issue with SinusBot.

https://forum.sinusbot.com/threads/cant-get-webstream-working.4315/
